### ISSUE TITLE
please is it possible to get the database file

### ISSUE THREAD

**Issue by kenneropia** [godbout/tailwindcss-dash-docset#19]
Please is it possible to get the already created "docSet.dsidx" file, im doing everything by hand except creating the datadase, cus i dont know sqlite, thanks.
![dd](https://user-images.githubusercontent.com/52609237/109834641-b4ec4180-7c42-11eb-9f53-a9aa1a187820.PNG)

**Comment by godbout** [comment]
wot m8.

**Comment by kenneropia** [comment]
What does "wot m" means?

**Comment by kenneropia** [comment]
What does "wot m" means?

**Comment by godbout** [comment]
just seeing your comment now, sorry. wot m8 means i have no idea what you're talking about.

**Comment by godbout** [comment]
there's a `docSet.dsidx` in the released packages. you can just check within the package content. but i have no idea what you mean by `doing everything by hand`. or is this a joke? is that you Marco???

**Comment by godbout** [comment]
ok bye
