### ISSUE TITLE
em unit conversions missing

### ISSUE THREAD

**Issue by rjhllr** [godbout/tailwindcss-dash-docset#30]
First off let me thank you so much for providing this docset, makes working Tailwind easy as :) just want to report this as it's a bit of a frustrating detail:

The official TailwindCSS Docs provide equivalents to em units with the default font size:
![image](https://user-images.githubusercontent.com/6401945/174046018-32740d57-2639-4553-8b96-6474822b8d20.png)
Same page in Dash doesn't:
![image](https://user-images.githubusercontent.com/6401945/174046104-ae3f38d1-0998-4735-ba85-2f32d4285892.png)

I may be able to contribute a PR, but just wanted to make sure it's reported somewhere for now.

**Comment by godbout** [comment]
my guess would be that this is new to the `3.1.x` version. currently the Dash Docset is up to `3.0.x`: https://github.com/godbout/tailwindcss-dash-docset/releases/tag/3.0.18

it's a bit of a pain to update tw. they always add some new funky stuff, JS, etc. not a priority for now, but will try to update this week.

thanks for the report.

**Comment by godbout** [comment]
btw not sure if you're aware but you can press `shift command b` when you're on a Docset to go to the online version. the Tailwind Docset handles this.

**Comment by godbout** [comment]
3.1.3 out: https://github.com/godbout/tailwindcss-dash-docset/releases/tag/3.1.3

i'll merge it into Dash in a few hours, should be available within Dash in a few days.

**Comment by godbout** [comment]
i didn't check thoroughly tho. i have a test suite and all tests passed. but regarding the UI, it's funky. you never know what they're adding/removing. you'll get your px tho :p

**Comment by godbout** [comment]
yeah i can see already some problem with the padding at the bottom of the page... well. good enough for now.

**Comment by rjhllr** [comment]
Wow, this is so cool of you. Thank you so much for that, also for the tip with Cmd+Shift+B that really saved me from the old "googling tailwindcss <component>" I was doing because of it. 

I think we may close this issue, really appreciate it!

**Comment by godbout** [comment]
yeah the `command shift b` is magic.

actually reopening for now. i'll not be able to live with that bad padding. will fix, push and update, merge to Dash, and will close again after.

**Comment by godbout** [comment]
> also for the tip with Cmd+Shift+B 

btw you can also use `command b` to launch the current Docset page in a browser locally. useful if you plan to make your own Docset or do some PRs.

**Comment by godbout** [comment]
padding fixed: https://github.com/godbout/tailwindcss-dash-docset/releases/tag/3.1.3.1
with tests. so will not happen the next time.

**Comment by godbout** [comment]
PR to Dash done: https://github.com/Kapeli/Dash-User-Contributions/pull/3749
