### ISSUE TITLE
Reverse index

### ISSUE THREAD

**Issue by jacobat** [godbout/tailwindcss-dash-docset#32]
Would it be possible to add a "reverse index" so that I could lookup the tailwind classes using this docset? It would be helpful to be able to be able to search for "flex-col" and get the documentation like you can on the Tailwind site.

**Comment by godbout** [comment]
pretty sure it would be possible yeah. the TOC is generated here: https://github.com/godbout/tailwindcss-dash-docset/blob/c846336b4b46143110b470874e394885436301f9/app/Docsets/TailwindCSS.php#L240

so you would just need to grab whatever selector(s) for the attributes that you're looking for.
but:
1. that will pollute the index/search capabilities
2. i have zero time and mental capacity to do it and test, etc. currently

**Comment by jacobat** [comment]
Got it. Thanks for the quick reply. And thanks for making this docset.

**Comment by godbout** [comment]
let's keep this issue open so that when/if i have time, i have a look.

**Comment by midnight-wonderer** [comment]
Hi @jacobat,
If you are still interested in the functionalities, the DocSet available on Dash's user_contrib repository has the indexes you mentioned. [See here](https://github.com/tailwindlabs/tailwindcss/discussions/2217#discussioncomment-11116024) for the details.

**Comment by jacobat** [comment]
I'm no longer a Dash user. Thanks though.

**Comment by godbout** [comment]
docset has been taken over: https://github.com/godbout/tailwindcss-dash-docset/issues/34
