### ISSUE TITLE
New docset for v3.3.3

### ISSUE THREAD

**Issue by knu** [godbout/tailwindcss-dash-docset#34]
Hi,

Are you still interested in updating this docset?  I've created a new docset for Tailwind CSS v3.3.3 which indexes all Tailwind CSS classes, modifiers, their CSS properties, functions, and directives.

https://github.com/knu/docset-tailwindcss/releases/

If it's acceptable to you, I'm willing to take on the role of the new maintainer of the Tailwind CSS docset in Dash-User-Contributions.

**Comment by godbout** [comment]
hey! thanks for reaching out.

yeah, i'm actually updating my docsets when 1) i'm actually heavily using them 2) someone requests. 
i've been slow lately on tw so i haven't updated for a while. can do it tho.

how's your own docset comparatively? does it index things better? more stuff? what i'd like to avoid is passing the maintenance of the docset, but having to wait if i want it updated 😂️ (which is why i started all my docsets, and my docset-builder).

if your docset is indeed better, then i may consider yeah. lemme know.

**Comment by knu** [comment]
Thanks for your quick reply.  My version includes entries for all individual Tailwind CSS classes like `p-2`, `mx-0.5` and `overflow-clip` as well as their corresponding CSS properties like `padding: 0.5rem`, `margin-left: 0.125rem`/`margin-right: 0.125rem` and `overflow: clip` so you can do lookup for reading and reverse-lookup for writing.  Modifiers like `sm:`, `hover:`, and `dark:` are also indexed.  As a learner who needs to catch up quickly, I needed them all.

You can download the docset from the above link, so please give it a try if you feel like it.
Direct link: https://github.com/knu/docset-tailwindcss/releases/download/v3.3.3/Tailwind_CSS.tgz

**Comment by godbout** [comment]
wow, sounds like you've indexed the whole thing 🤣️🤣️🤣️ doesn't pollute the search?

anyways. thanks. will check later today and will let you know by tomorrow the latest.

**Comment by godbout** [comment]
ok yours is clearly better 😂️😂️😂️
i mean i'm not sure in term of day to day usage? maybe there's too much info. but it looks very clean and well indexed. so yeah, please run yours.

it'd be nice i think—although not necessary—to keep the credits from the previous maintainers. when i took over from Ben, i kept his name first in the list of contributors to the Tailwind CSS package when you download it. also his contact etc. is still there in the README for up to v 0.7.4 (if i remember well).

anyways. thanks for having reached out!

**Comment by knu** [comment]
Thank you very much for promptly taking the time to review my version!  I greatly appreciate it and am thankful for your generous offer to hand over the maintainership.

Of course, I will certainly ensure to preserve the credit and mention, and I intend to incorporate more of the good parts of your version into mine.  Once it's done, I will submit a pull request to the Dash-User-Contributions repository and make sure to mention you.  Thank you again!

**Comment by godbout** [comment]
my pleasure. have a lot of fun!

**Comment by atimmer** [comment]
It seems that the new version has a weird interaction with light/dark mode in Dash. 

Dash in Light mode:
<img width="1268" alt="Screenshot 2023-10-19 at 14 22 19" src="https://github.com/godbout/tailwindcss-dash-docset/assets/584693/86f9dffc-bd07-414a-928c-5a263770c3c0">

Dash in Dark mode:
<img width="1312" alt="Screenshot 2023-10-19 at 14 22 24" src="https://github.com/godbout/tailwindcss-dash-docset/assets/584693/513519c1-9465-4d48-b6fa-1d711218ce11">

In the previous version, the light mode looked like the website:
<img width="754" alt="Screenshot 2023-10-19 at 14 24 06" src="https://github.com/godbout/tailwindcss-dash-docset/assets/584693/a2fb6336-d0ff-417c-8ef7-aa3c74f60da2">

**Comment by knu** [comment]
Thanks.  This is caused by the original document statically built with `darkMode: 'class'`.
https://github.com/tailwindlabs/tailwindcss.com/blob/master/tailwind.config.js

I think I could add some piece of JavaScript to dynamically toggle the `dark` class of `<html>`.  Please stay tuned for the next release.

**Comment by knu** [comment]
The latest build has been released, so update the docset in Dash and give it a try.
If there are any issues, please report them to my repository next time.  Thanks!

**Comment by atimmer** [comment]
@knu Thanks! Works like a charm.
